{
 "title": "Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "HTTP Request Duration (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{app=~\"eu|us\", path!=\"/health\"}[1m])) by (le, app))",
     "legendFormat": "{{app}} (95th percentile)"
    }
   ]
  },
  {
   "title": "Total HTTP Requests (excluding /health) over 1m",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{app=~\"eu|us\", path!=\"/health\"}[1m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Resident Memory" }
   ]
  },
  {
   "title": "Heap Memory Allocated",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "Heap Allocated" }
   ]
  },
  {
   "title": "Average GC Pause Duration (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum[1m]) / rate(go_gc_duration_seconds_count[1m])",
     "legendFormat": "Avg GC Pause Duration"
    }
   ]
  },
  {
   "title": "CPU Time Spent",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "CPU Seconds Total" }
   ]
  }
 ]
}