# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: geoip-ingressroute
#   namespace: default
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: Host(`api.lb`) && HeadersRegexp(`X-Continent-Code`, `^EU$`)
#       kind: Rule
#       priority: 100
#       services:
#         - name: eu-remote-service
#           kind: Service
#           port: 443
#           scheme: https
#           serversTransport: api-transport
#       middlewares:
#         - name: geoip2
#           namespace: default
#         - name: eu-host-header
#           namespace: default

#     - match: Host(`api.lb`)
#       kind: Rule
#       priority: 1
#       services:
#         - name: us-remote-service
#           kind: Service
#           port: 443
#           scheme: https
#           serversTransport: api-transport
#       middlewares:
#         - name: geoip2
#           namespace: default
#         - name: us-host-header
#           namespace: default
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: geoip-debug
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.lb`)
      kind: Rule
      services:
        - name: httpbin
          kind: Service
          port: 80
      middlewares:
        - name: geoip2
          namespace: default
