{{- if .Values.ingress.enabled -}}
{{- if eq .Values.ingress.className "traefik" -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    {{- range .Values.ingress.hosts }}
    - match: HostRegexps(`{{ .host }}`)
      kind: Rule
      services:
        - name: {{ include "api.fullname" $ }}
          port: {{ $.Values.service.port }}
          scheme: https
          serversTransport: api-transport
    {{- end }}
    # Fallback route: catch all
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ include "api.fullname" . }}
          port: {{ .Values.service.port }}
          scheme: https
          serversTransport: api-transport
  tls:
    secretName: api-tls
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  namespace: {{ .Release.Namespace }}
  name: api-transport
spec:
  insecureSkipVerify: true
{{- end -}}
{{- end -}}
