{{- if .Values.ingress.enabled -}}
{{- if eq .Values.ingress.className "traefik" -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    {{- range .Values.ingress.hosts }}
    - match: Host(`{{ .host }}`)
      kind: Rule
      services:
        - name: {{ include "api.fullname" $ }}
          port: {{ $.Values.service.port }}
          scheme: https
          serversTransport: api-transport
    {{- end }}
  tls:
    passthrough: true  # Since the go api is already handling https we need to do so to use traefik as just a reverse proxy without tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: api-transport
spec:
  insecureSkipVerify: true
{{- end -}}
{{- end -}}