apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-us-cert
  namespace: ${namespace}
spec:
  secretName: ${secret_name}
  commonName: ${common_name}
  dnsNames:
    - ${common_name}
  issuerRef:
    name: ${issuer_name}
    kind: ClusterIssuer
